### ISSUE TITLE
"Goto Definition" context menu doesn't work with French translation

### ISSUE THREAD

**Issue by pwozniak89** [zam1024t/LocalizedMenu#28]
Since last update I've got an issue with Context menu...

When I do right click on a function the "Goto Definition" submenu is disabled when I use French translation.
It works great with "en", "en_GB", "en_US", "es_ES", "de_DE" but not with "fr_FR", "ru_RU", "pt_BR", "hy", "sv_SE"
An accents issue ???

Could you help me/us ?

**Comment by zam1024t** [comment]
The menu item disabled because sublime has no command for `context_goto_definition` which has rename to `goto_definition` in ST4.
No one has translate "ru_RU", "pt_BR", "hy", "sv_SE" for ST4, so the last ST3 menu be used.

https://github.com/zam1024t/LocalizedMenu/blob/v1.6.4/menu/4126/de_DE/Context.sublime-menu.json#L4
https://github.com/zam1024t/LocalizedMenu/blob/v1.6.4/menu/4126/fr_FR/Context.sublime-menu.json#L7

Please upgrade to v1.6.5, this issues resloved.

**Comment by pwozniak89** [comment]
It works !
Thanks.
